apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-probe-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-probe-tester
  template:
    metadata:
      labels:
        app: python-probe-tester
    spec:
      containers:
      - name: python-probe-tester
        image: shubhindia/probe-tester:python
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-probe-tester
spec:
  selector:
    app: python-probe-tester
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort